### ISSUE TITLE
I'm thinking of doing something similar for the KLC - how did you generate these wallpapers?

### ISSUE THREAD

**Issue by SecondReality** [alb404/JLPT-one-kanji-a-day-wallpaper-set#1]

**Comment by alb404** [comment]
Hi. I did it manually taking screen shots of a restyled version of the kanji listing they have on http://www.jlptstudy.net/

**Comment by htadashi** [comment]
@SecondReality Based on alb404 cool idea, I made an [Anki plugin](https://github.com/htadashi/anki-kanji-wallpaper-generator) to generate wallpapers from anki cards. You can adapt this plugin (it is a python script) to generate custom wallpapers from your personal list of kanjis.
